---
future: true
title: "L'Amore Chiama! TOUR | 5pani2pesci"
description: "L'Amore Chiama! Incontri sull'affettività e il discernimento vocazionale."
url_5pani2pesci: https://5p2p.it
url: https://tour.5p2p.it
baseurl: ''
timezone: UTC
permalink: "/:title:year/"
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:title/"
  posts:
    title: Posts
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
exclude: [.git]
# plugins:
#   - jekyll-redirect-from
